# Generated by Django 5.1.7 on 2026-06-30 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPipelineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100, unique=True)),
                ('institution_name', models.CharField(default='University of Kigali', max_length=255)),
                ('auto_dispatch_threshold', models.FloatField(default=0.82)),
                ('escalation_threshold', models.FloatField(default=0.65)),
                ('reviewer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('email_dispatch_mode', models.CharField(choices=[('dry_run', 'Dry run'), ('smtp', 'SMTP'), ('external_api', 'External API')], default='dry_run', max_length=20)),
                ('classifier_endpoint', models.URLField(blank=True, default='')),
                ('generator_endpoint', models.URLField(blank=True, default='')),
                ('dispatch_endpoint', models.URLField(blank=True, default='')),
                ('reply_signature', models.TextField(blank=True, default='University of Kigali Automated Response System')),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Pipeline Config',
                'verbose_name_plural': 'Email Pipeline Configs',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('attachment', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('original_payload', models.JSONField(blank=True, default=dict)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('source_channel', models.CharField(default='email', max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('REVIEW', 'Needs Review'), ('REPLIED', 'Replied'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('auto_dispatch', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_text', models.TextField()),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('model_name', models.CharField(default='heuristic-t5-adapter', max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('dispatch_status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('dispatched_to', models.EmailField(blank=True, default='', max_length=254)),
                ('dispatch_error', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_response', to='emails.email')),
            ],
        ),
        migrations.CreateModel(
            name='AI_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('comment', models.TextField(blank=True)),
                ('feedback_source', models.CharField(default='staff', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_feedback', to=settings.AUTH_USER_MODEL)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='emails.email')),
            ],
        ),
        migrations.CreateModel(
            name='EmailClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ADMISSION', 'Admission inquiry'), ('FEES', 'Fee and payment query'), ('REGISTRATION', 'Course registration & academic calendar'), ('EXAM', 'Examination and results inquiry'), ('ADMIN', 'General administrative request')], max_length=30)),
                ('confidence_score', models.FloatField()),
                ('model_name', models.CharField(default='heuristic-bert-adapter', max_length=100)),
                ('rationale', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='emails.email')),
            ],
        ),
        migrations.CreateModel(
            name='EmailDispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='QUEUED', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_logs', to='emails.email')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_logs', to='emails.airesponse')),
            ],
        ),
        migrations.CreateModel(
            name='EmailReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrected_response', models.TextField()),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EDITED', 'Edited')], default='PENDING', max_length=20)),
                ('reviewer_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='emails.email')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
