# Generated by Django 5.1.7 on 2026-06-30 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_email', models.TextField()),
                ('expected_category', models.CharField(choices=[('ADMISSION', 'Admission inquiry'), ('FEES', 'Fee and payment query'), ('REGISTRATION', 'Course registration & academic calendar'), ('EXAM', 'Examination and results inquiry'), ('ADMIN', 'General administrative request')], max_length=30)),
                ('expected_response', models.TextField()),
                ('anonymized', models.BooleanField(default=True)),
                ('pii_removed', models.BooleanField(default=True)),
                ('source', models.CharField(default='manual_annotation', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_data_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
