# Generated by Django 5.1.7 on 2026-06-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditLog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User login'), ('LOGOUT', 'User logout'), ('USER_CREATE', 'User created'), ('USER_UPDATE', 'User updated'), ('USER_DELETE', 'User deleted'), ('USER_ACTIVATE', 'User activated'), ('USER_DEACTIVATE', 'User deactivated'), ('PASSWORD_RESET_REQUEST', 'Password reset requested'), ('PASSWORD_RESET_COMPLETE', 'Password reset completed'), ('PROFILE_UPDATE', 'Profile updated'), ('PERMISSION_CHANGE', 'User permissions changed'), ('EMAIL_RECEIVED', 'Email received'), ('EMAIL_CLASSIFIED', 'Email classified'), ('EMAIL_REVIEW_REQUESTED', 'Email sent for human review'), ('EMAIL_REVIEWED', 'Email reviewed'), ('EMAIL_REPLIED', 'Email replied'), ('EMAIL_DISPATCHED', 'Email dispatched'), ('EMAIL_DISPATCH_FAILED', 'Email dispatch failed'), ('EMAIL_FEEDBACK_CAPTURED', 'Email feedback captured'), ('TRAINING_DATA_CREATED', 'Training data created'), ('PIPELINE_CONFIG_UPDATED', 'Pipeline config updated')], max_length=50),
        ),
    ]
